### ISSUE TITLE
Does this use the video analysis?

### ISSUE THREAD

**Issue by EXJUSTICE** [gbmksquare/Realtime-Video-Emotion#1]
Hi,

Out of curiosity, is the real time video stream simply taking snapshots, or actually analyzing video?

**Comment by gbmksquare** [comment]
Hello, this project does not actually use video analysis because video API requires uploading full video.

In this project, frames are grabbed in every fixed duration and uses photo API to find face in the photo. Also, there is a max rate per minute (free plan), so the rate of capture per minute is not too high.

**Comment by EXJUSTICE** [comment]
Thanks for the rapid reply man. After closer examination of the documentation, I don't think the video version is that good, as it averages and reports out a SINGLE value for each emotion.

I will implement something similiar for java, thanks again

**Comment by gbmksquare** [comment]
Great! By the way if you are using paid plan, you should be able to grab more frames per minutes to analyze.
